In [1]:
import tensorflow as tf

In [2]:
tensor_one_d = tf.constant([1,2,3,4,5])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [3]:
tensor_two_d = tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [19]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [3,4,5]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 4 5]]], shape=(2, 2, 3), dtype=int32)


Converting numpy array to tensor

In [6]:
import numpy as np

In [8]:
np_array = np.array([1,2,3,4,5])
tensor_array = tf.convert_to_tensor(np_array)
print(tensor_array)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


Identity matrix

In [16]:
i_matrix = tf.eye(
    num_rows = 3,
    num_columns = 3,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)
print(i_matrix)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [18]:
i_matrix = tf.eye(
    num_rows = 3,
    num_columns = 3,
    batch_shape = [2,],
    dtype = tf.dtypes.float32,
    name = None
)
print(i_matrix)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


# tf.fill method


In [20]:
tf.fill(
    dims = [3,2], value = 1, name=None, layout=None
)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

tf.ones()

In [22]:
tf.ones(
    shape = [4,2],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

# tf.zeros

In [23]:
tf.zeros(
    shape = [4,3],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>